# Generated by Django 3.2.7 on 2021-09-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя_Автора'),
        ),
    ]
